#!/usr/bin/env python3

# Check that the make command don't execute any rules and had an unexpected error

import time
import sys
import os
import subprocess

os.environ["DEBUG"] = "TRUE"
p = subprocess.Popen(["make"] + sys.argv[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
time.sleep(10)
if p.poll() is None:
    p.kill()
    print("The second make run take too long, probably a task is running again")
    subprocess.call(["make"] + sys.argv[1:])
    exit(2)
exit(p.returncode)
